
import React, { useState } from 'react';
import { AppendixEntry, FullCharacter } from '../types';

interface Props {
  appendixEntries: AppendixEntry[];
  characters: FullCharacter[];
  onVaultConnected: (handle: FileSystemDirectoryHandle) => void;
  vaultHandle: FileSystemDirectoryHandle | null;
}

const ObsidianSync: React.FC<Props> = ({ appendixEntries, characters, onVaultConnected, vaultHandle }) => {
  const [syncing, setSyncing] = useState(false);
  const [message, setMessage] = useState("");

  const connectVault = async () => {
    try {
      const handle = await (window as any).showDirectoryPicker({
        mode: 'readwrite'
      });
      onVaultConnected(handle);
      setMessage(`Connected to: ${handle.name}`);
    } catch (err) {
      console.error("Vault connection failed", err);
      setMessage("Connection cancelled or failed.");
    }
  };

  const ensureDirectory = async (parent: FileSystemDirectoryHandle, name: string) => {
    return await parent.getDirectoryHandle(name, { create: true });
  };

  const writeMarkdown = async (dir: FileSystemDirectoryHandle, fileName: string, content: string) => {
    const fileHandle = await dir.getFileHandle(`${fileName}.md`, { create: true });
    const writable = await (fileHandle as any).createWritable();
    await writable.write(content);
    await writable.close();
  };

  const syncAll = async () => {
    if (!vaultHandle) return;
    setSyncing(true);
    setMessage("Syncing to Obsidian...");

    try {
      const rootDir = await ensureDirectory(vaultHandle, "Shan Zhou");
      const loreDir = await ensureDirectory(rootDir, "Lore");
      const charDir = await ensureDirectory(rootDir, "Characters");

      // Sync Appendix
      for (const entry of appendixEntries) {
        const frontmatter = `---
category: ${entry.category}
tags: [pf2e, shan-zhou, ${entry.category.toLowerCase()}]
updated: ${new Date(entry.timestamp).toISOString()}
---
# ${entry.title}

${entry.content}`;
        const safeName = entry.title.replace(/[/\\?%*:|"<>]/g, '-');
        await writeMarkdown(loreDir, safeName, frontmatter);
      }

      // Sync Characters
      for (const char of characters) {
        const charSheet = `---
tags: [pf2e, character, hero]
level: ${char.level}
class: ${char.class}
ancestry: ${char.ancestry}
---
# ${char.name}

## Vitals
- **Level**: ${char.level}
- **Ancestry**: ${char.ancestry} (${char.heritage})
- **Background**: ${char.background}
- **Class**: ${char.class}

## Stats
- STR: ${char.stats.str}
- DEX: ${char.stats.dex}
- CON: ${char.stats.con}
- INT: ${char.stats.int}
- WIS: ${char.stats.wis}
- CHA: ${char.stats.cha}

## Notes
${char.notes}

---
*Generated by Shan' Zhou Solo Toolbox*`;
        const safeName = char.name.replace(/[/\\?%*:|"<>]/g, '-');
        await writeMarkdown(charDir, safeName, charSheet);
      }

      setMessage("Sync Complete! Check your Obsidian vault.");
    } catch (err) {
      console.error("Sync failed", err);
      setMessage("Sync error. Check permissions.");
    } finally {
      setSyncing(false);
      setTimeout(() => setMessage(""), 5000);
    }
  };

  return (
    <div className="bg-[#1a1a1a] border border-[#333] p-6 rounded-lg shadow-inner">
      <div className="flex items-center justify-between mb-4">
        <h4 className="text-[#9b59b6] font-black uppercase text-xs tracking-widest flex items-center gap-2">
          <span className="text-lg">💎</span> Obsidian Vault Integration
        </h4>
        {vaultHandle && (
          <span className="text-[9px] font-black bg-green-900/20 text-green-500 px-2 py-0.5 rounded border border-green-500/30 uppercase">
            Vault Linked
          </span>
        )}
      </div>

      <p className="text-[10px] text-gray-500 leading-relaxed mb-6">
        Connect your local Obsidian vault to automatically sync Lore, People, and Places as Markdown files. 
        This uses the Web File System Access API to write directly to your vault's folder.
      </p>

      {!vaultHandle ? (
        <button 
          onClick={connectVault}
          className="w-full bg-[#9b59b6] hover:bg-[#8e44ad] text-white font-black py-3 rounded text-[10px] uppercase tracking-[0.2em] shadow-lg transition-all active:scale-95"
        >
          Connect Obsidian Vault
        </button>
      ) : (
        <div className="space-y-3">
          <button 
            onClick={syncAll}
            disabled={syncing}
            className={`w-full py-3 rounded text-[10px] font-black uppercase tracking-[0.2em] shadow-lg transition-all flex items-center justify-center gap-2 ${
              syncing 
              ? 'bg-[#2a2a2a] text-gray-600 cursor-not-allowed' 
              : 'bg-white text-black hover:bg-gray-200 active:scale-95'
            }`}
          >
            {syncing ? 'Synchronizing...' : '⚡ Sync All to Vault'}
          </button>
          <button 
            onClick={() => onVaultConnected(null as any)}
            className="w-full border border-red-900/30 text-red-500 py-2 rounded text-[9px] font-black uppercase hover:bg-red-900/10 transition-colors"
          >
            Disconnect Vault
          </button>
        </div>
      )}

      {message && (
        <div className="mt-4 p-3 bg-black/40 border border-[#333] rounded text-center animate-in fade-in duration-300">
          <p className="text-[9px] font-bold text-gray-400 uppercase tracking-wider italic">{message}</p>
        </div>
      )}
    </div>
  );
};

export default ObsidianSync;
